services:
  web:
#    entrypoint: sh start.sh
#    command: uvicorn main:app --port 8009 --host 0.0.0.0 --reload
    build:
      context: .
    volumes:
      - .:/FA9
    ports:
      - '8009:8009'
    working_dir: /FA9
    privileged: true
    restart: on-failure
    environment:
      - PYTHONPATH = / # fixing python path when changing the working directory
      - WATCHFILES_FORCE_POLLING=true # This is needed for hot reloading to work on windows  (fix watch feature) for python
      - WATCHPACK_POLLING=true # This is needed for hot reloading to work on windows  (fix watch feature)
      - CHOKIDAR_USEPOLLING=true # This is needed for hot reloading to work on windows (fix watch feature)
      - FORCE_COLOR="1" # This forces colors in the terminal + fix chalk colors
      - PYTHONUNBUFFERED=1 # This stops Python from buffering stdout so that you can see logs in real-time